### ISSUE TITLE
`@localCopy` throws "same computation" assertion for Ember 3.16

### ISSUE THREAD

**Issue by simonihmig** [tracked-tools/tracked-toolbox#17]
Refactored a component to Glimmer, and used `@localCopy` for the behavior previously implemented with a CP. This however throws the following assertion in some cases at this [line](https://github.com/pzuraq/tracked-toolbox/blob/master/addon/index.js#L53)

```
Error: Assertion Failed: You attempted to update `value` on `Meta`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.
```

The best reproduction I have at hand is this [PR](https://github.com/kaliber5/ember-bootstrap/pull/1226). The full error stack can be seen in CI [here](https://github.com/kaliber5/ember-bootstrap/pull/1226/checks?check_run_id=1080278222#step:5:78).

A brief outline how things work together here:
1. `isSelected` is defined to be a local copy of `this.args.selected` [here](https://github.com/kaliber5/ember-bootstrap/pull/1226/files#diff-5f930d7a78ee79cf9092c8e0722cff94R67)
2. `isSelected` is passed down to a sub component [here](https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-accordion.hbs#L8)
3. the sub component consumes this (as `this.args.selected`) in this getter [here](https://github.com/kaliber5/ember-bootstrap/pull/1226/files#diff-fad8ca858787e25f4e4d0623b3c60caeR65). *Note when I remove reading from `this.args.selected` here, the error is not thrown anymore, but of course the component does not work correctly anymore. But at least it shows the definite place where the original localCopied property is consumed...*
4. when setting a property passed to `@selected` (of the parent component, see 1.) [here](https://github.com/kaliber5/ember-bootstrap/blob/master/tests/integration/components/bs-accordion-test.js#L82), the mentioned assertion is thrown.

Note 1: this only happens for Ember 3.16 (or eventually more versions not covered by ember-try scenarios). It does *not* happen for 3.20, or the current release, beta or canary scenarios! So maybe the root issue is in that version of Ember, and has been fixed later?

Note 2: Previously the Ember.Component based implementation used a very simple CP-based solution for the same behavior as `localCopy` [here](https://github.com/kaliber5/ember-bootstrap/blob/master/addon/utils/cp/listen-to.js), which did not suffer from this.

Note 3: similar sounding issue report in https://github.com/pzuraq/tracked-toolbox/issues/7

**Comment by simonihmig** [comment]
I tracked this down a bit further regarding the Ember versions: 3.16 (didn't test earlier versions) to 3.20.3 show this error, but starting from 3.20.4 this seems fixed. Not sure what change could have caused, maybe just on of the GlimmerVM updates? https://github.com/emberjs/ember.js/blob/master/CHANGELOG.md#v3204-august-11-2020

Given that I need to support 3.16, and this addon says it supports 3.8, it would be nice to get this fixed nevertheless. 

@pzuraq do you see any chance, or is this something that can only be fixed upstream? (I assume the changes that fixed this in 3.20.4 won't get backported to 3.16, even though it's still an active LTS?)

**Comment by jelhan** [comment]
I tried to verify if it's related to the Glimmer VM updates. It doesn't seem so.

`ember-source@3.20.3` uses `^0.55.1` and `ember-source@3.20.4` uses `^0.56.1`. I run the feature branch reproducing the issue (https://github.com/kaliber5/ember-bootstrap/pull/1226) against both versions. I can confirm that `v3.20.3` is failing, while `v3.20.4` is passing.

To verify if it's related to Glimmer VM updates I used yarn resolutions to enforce Glimmer VM `^0.56.1` with `ember-source@3.20.3`:

```patch
diff --git a/package.json b/package.json
index 9335edbb..e5832aac 100644
--- a/package.json
+++ b/package.json
@@ -103,7 +103,7 @@
     "ember-resolver": "^8.0.2",
     "ember-sinon": "^5.0.0",
     "ember-sinon-qunit": "^5.0.0",
-    "ember-source": "~3.20.4",
+    "ember-source": "3.20.3",
     "ember-source-channel-url": "^3.0.0",
     "ember-template-lint": "^2.11.0",
     "ember-try": "^1.4.0",
@@ -179,5 +179,15 @@
   },
   "lint-staged": {
     "*.js": "eslint --cache --fix"
+  },
+  "resolutions": {
+    "@glimmer/compiler": "^0.56.1",
+    "@glimmer/interfaces": "^0.56.1",
+    "@glimmer/node": "^0.56.1",
+    "@glimmer/opcode-compiler": "^0.56.1",
+    "@glimmer/program": "^0.56.1",
+    "@glimmer/reference": "^0.56.1",
+    "@glimmer/runtime": "^0.56.1",
+    "@glimmer/validator": "^0.56.1"
   }
 }
```

Tests are still failing.

I verified that `v0.56.1` is actually used:

```
$ yarn list --pattern "@glimmer|ember-source"
yarn list v1.22.5
├─ @glimmer/component@1.0.1
│  └─ @glimmer/util@0.44.0
├─ @glimmer/di@0.1.11
├─ @glimmer/encoder@0.56.1
├─ @glimmer/env@0.1.7
├─ @glimmer/interfaces@0.56.1
├─ @glimmer/low-level@0.56.1
├─ @glimmer/program@0.56.1
├─ @glimmer/reference@0.56.1
├─ @glimmer/runtime@0.56.1
├─ @glimmer/syntax@0.54.2
│  └─ @glimmer/util@0.54.2
├─ @glimmer/tracking@1.0.1
├─ @glimmer/util@0.56.1
├─ @glimmer/validator@0.56.1
├─ @glimmer/vm@0.56.1
├─ @glimmer/wire-format@0.56.1
├─ ember-cli@3.20.0
│  └─ ember-source-channel-url@2.0.1
├─ ember-source-channel-url@3.0.0
├─ ember-source@3.20.3
├─ ember-try-config@3.0.0
│  └─ ember-source-channel-url@1.2.0
└─ wrap-legacy-hbs-plugin-if-needed@1.0.1
   ├─ @glimmer/syntax@0.42.2
   └─ @glimmer/util@0.42.2
Done in 1.03s.
```

To double check I compared the installed packages for `ember-source@3.20.4`, for which the feature branch is passing. No difference except for `ember-source` on that packages:

```
$ yarn list --pattern "@glimmer|ember-source"
yarn list v1.22.5
├─ @glimmer/component@1.0.1
│  └─ @glimmer/util@0.44.0
├─ @glimmer/di@0.1.11
├─ @glimmer/encoder@0.56.1
├─ @glimmer/env@0.1.7
├─ @glimmer/interfaces@0.56.1
├─ @glimmer/low-level@0.56.1
├─ @glimmer/program@0.56.1
├─ @glimmer/reference@0.56.1
├─ @glimmer/runtime@0.56.1
├─ @glimmer/syntax@0.54.2
│  └─ @glimmer/util@0.54.2
├─ @glimmer/tracking@1.0.1
├─ @glimmer/util@0.56.1
├─ @glimmer/validator@0.56.1
├─ @glimmer/vm@0.56.1
├─ @glimmer/wire-format@0.56.1
├─ ember-cli@3.20.0
│  └─ ember-source-channel-url@2.0.1
├─ ember-source-channel-url@3.0.0
├─ ember-source@3.20.4
├─ ember-try-config@3.0.0
│  └─ ember-source-channel-url@1.2.0
└─ wrap-legacy-hbs-plugin-if-needed@1.0.1
   ├─ @glimmer/syntax@0.42.2
   └─ @glimmer/util@0.42.2
Done in 2.12s.
```

Not sure if I missed something. Tried to document my steps as detailed as possible so that you can verify if my findings are correct.

**Comment by chriskrycho** [comment]
Given this is resolved on current versions of Ember, and that the latest version of the library requires at least Ember 3.24, I'm closing this. Folks who hit it should upgrade Ember to the current LTS (which is the best path forward for folks just starting on Octane anyway)!
