### ISSUE TITLE
Is it possible for @localCopy to always update the local value when the remote value is set?

### ISSUE THREAD

**Issue by trevordevore** [tracked-tools/tracked-toolbox#210]
Currently @localCopy only updates the local value if the remote value is changed. Setting the remote value to the same value it is currently set to does not update the local value. Would it be possible to add a 3rd parameter that would alter the behavior so that the local value is always updated?

There is at least one scenario where always updating the local value whenever the remote value is set is desirable. Think of an Accordion component whose AccordionItem components each have an `isOpen` property which affects visibility. The accordion component may want to force all AccordionItems into a specific state (open or closed). Think of buttons to Expand All and Collapse All. 

The desirable interface would be a `@forceState` argument passed into the Accordion component which is then passed into each AccordionItem component. The AccordionItem `isOpen` property should be initialized to the value of `@forcedState` if present. If `@forcedState` is then updated later on because the user clicks on Expand All or Collapse All then `isOpen` in each AccordionItem should be updated.

With the current design of `@localCopy` the following bug exists in the Accordion:

1. Click on AccordionItem 1 to expand.
2. Click on Collapse All button which sets `@forceState` to `false` which in turn closes AccordionItem 1 because `isOpen` is set to `false`.
3. Click on Accordionitem 1 and AccordionItem 2 to expand.
4. Click on Collapse All button which sets `@forceState` to `false`. Since `@forceState` is already set to `false` AccordionItem 1 and 2 remain open because `@localCopy` does not update the local values of `isOpen`.

Looking at the existing code it doesn't appear that the `@localCopy` `get()` function knows if it was the local or remote value that triggered the call. Without knowing that setting the remote value triggered the call I don't know the current `@localCopy` behavior could be changed. Perhaps I'm missing something though?

**Comment by SergeAstapov** [comment]
> Without knowing that setting the remote value triggered the call I don't know the current `@localCopy` behavior could be changed.

@trevordevore this is exactly the problem why I'm not sure this is possible. Reactivity system tell you when thins change, but you don't know which things have changed

in your use case, I guess you just need to find another pattern that will achieve desired result.

**Comment by trevordevore** [comment]
Thanks for confirming @SergeAstapov. I have another approach which I'll use.
