### ISSUE TITLE
Plan for v2 release

### ISSUE THREAD

**Issue by SergeAstapov** [tracked-tools/tracked-toolbox#65]
An outline of what I think needs to be done for a v2 release:

* [ ] ~~cut minor v1.3.0 bundling up all the stuff done lately~~
* [x] #64 
* [x] #66 
* [x] #68
* [x] cut major v2.0.0

**Comment by SergeAstapov** [comment]
@chriskrycho would you mind to cut and publish v1.3.0 release? so we can proceed with https://github.com/tracked-tools/tracked-toolbox/pull/64

**Comment by chriskrycho** [comment]
Cutting 1.3.0 now, thanks!

**Comment by chriskrycho** [comment]
**Update:** we technically have a breaking change in the mix courtesy of #44. I'm going to go ahead and roll in the *other* breaking changes (requiring Node 14+, requiring ember-auto-import, etc.), remove deprecated code, etc.—as with tracked-built-ins we can cut a 2.0 which requires consumers to have ember-auto-import and then ship the Embroider v2 addon format after.

**Comment by chriskrycho** [comment]
Done in [v2.0.0](https://github.com/tracked-tools/tracked-toolbox/releases/tag/v2.0.0).
